# Generated by Django 3.1.4 on 2020-12-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedTracesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('TestName', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Uploaded Trace',
                'verbose_name_plural': 'Uploaded Traces',
            },
        ),
    ]
