# Generated by Django 3.1.4 on 2020-12-01 18:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analyzerApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedtracesmodel',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.AddField(
            model_name='uploadedtracesmodel',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='photos/'),
            preserve_default=False,
        ),
    ]
