# Generated by Django 3.1.4 on 2020-12-01 20:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analyzerApp', '0002_auto_20201201_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedtracesmodel',
            name='file',
        ),
        migrations.AddField(
            model_name='uploadedtracesmodel',
            name='realFileName',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedtracesmodel',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedtracesmodel',
            name='TestName',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
