# Generated by Django 3.1.4 on 2020-12-01 22:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analyzerApp', '0006_auto_20201201_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedtracesmodel',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
