# Generated by Django 3.1.4 on 2020-12-19 20:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analyzerApp', '0007_auto_20201201_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzerScenarioModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scenarioName', models.CharField(max_length=100, unique=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Analyzer Scenario',
                'verbose_name_plural': 'Analyzer Scenario',
            },
        ),
    ]
