# Generated by Django 3.1.4 on 2020-12-19 20:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analyzerApp', '0008_analyzerscenariomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzerscenariomodel',
            name='scenarioDescription',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
