# Generated by Django 3.1.4 on 2020-12-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzerApp', '0009_analyzerscenariomodel_scenariodescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzerscenariomodel',
            name='scenarioDescription',
            field=models.CharField(max_length=100),
        ),
    ]
