import pymongo
client = pymongo.MongoClient('mongodb://172.17.0.3:27017/')
db = client['diagram']
col = db["ngapForm"]


ProcedureCodes = {
        '0'  : {'name': 'AMFConfigurationUpdate', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '1'  : {'name': 'AMFStatusIndication', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '2'  : {'name': 'CellTrafficTrace', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '3'  : {'name': 'DeactivateTrace', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '4'  : {'name': 'DownlinkNASTransport', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '5'  : {'name': 'DownlinkNonUEAssociatedNRPPaTransport', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '6'  : {'name': 'DownlinkRANConfigurationTransfer', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '7'  : {'name': 'DownlinkRANStatusTransfer', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '8'  : {'name': 'DownlinkUEAssociatedNRPPaTransport', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '9'  : {'name': 'ErrorIndication', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '10' : {'name': 'HandoverCancel', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '11' : {'name': 'HandoverNotification', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '12' : {'name': 'HandoverPreparation', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '13' : {'name': 'HandoverResourceAllocation', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '14' : {'name': 'InitialContextSetup', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '15' : {'name': 'InitialUEMessage', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '16' : {'name': 'LocationReportingControl', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '17' : {'name': 'LocationReportingFailureIndication', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '18' : {'name': 'LocationReport', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '19' : {'name': 'NASNonDeliveryIndication', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '20' : {'name': 'NGReset', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '21' : {'name': 'NGSetup', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '22' : {'name': 'OverloadStart', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '23' : {'name': 'OverloadStop', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '24' : {'name': 'Paging', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '25' : {'name': 'PathSwitchRequest', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '26' : {'name': 'PDUSessionResourceModify', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '27' : {'name': 'PDUSessionResourceModifyIndication', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '28' : {'name': 'PDUSessionResourceRelease', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '29' : {'name': 'PDUSessionResourceSetup', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '30' : {'name': 'PDUSessionResourceNotify', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '31' : {'name': 'PrivateMessage', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '32' : {'name': 'PWSCancel', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '33' : {'name': 'PWSFailureIndication', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '34' : {'name': 'PWSRestartIndication', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '35' : {'name': 'RANConfigurationUpdate', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '36' : {'name': 'RerouteNASRequest', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '37' : {'name': 'RRCInactiveTransitionReport', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '38' : {'name': 'TraceFailureIndication', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '39' : {'name': 'TraceStart', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '40' : {'name': 'UEContextModification', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '41' : {'name': 'UEContextRelease', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '42' : {'name': 'UEContextReleaseRequest', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '43' : {'name': 'UERadioCapabilityCheck', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '44' : {'name': 'UERadioCapabilityInfoIndication', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '45' : {'name': 'UETNLABindingRelease', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '46' : {'name': 'UplinkNASTransport', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '47' : {'name': 'UplinkNonUEAssociatedNRPPaTransport', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '48' : {'name': 'UplinkRANConfigurationTransfer', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '49' : {'name': 'UplinkRANStatusTransfer', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '50' : {'name': 'UplinkUEAssociatedNRPPaTransport', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '51' : {'name': 'WriteReplaceWarning', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '52' : {'name': 'SecondaryRATDataUsageReport', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '53' : {'name': 'UplinkRIMInformationTransfer', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '54' : {'name': 'DownlinkRIMInformationTransfer', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '55' : {'name': 'RetrieveUEInformation', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '56' : {'name': 'UEInformationTransfer', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '57' : {'name': 'RANCPRelocationIndication', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '58' : {'name': 'UEContextResume', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '59' : {'name': 'UEContextSuspend', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '60' : {'name': 'UERadioCapabilityIDMapping', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '61' : {'name': 'HandoverSuccess', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '62' : {'name': 'UplinkRANEarlyStatusTransfer', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '63' : {'name': 'DownlinkRANEarlyStatusTransfer', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '64' : {'name': 'AMFCPRelocationIndication', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
        '65' : {'name': 'ConnectionEstablishmentIndication', 'required': True, 'filter': False, 'fields': [], 'ShowOnMainLine': False},
    }


x = col.delete_one({"_id":1})
x = col.delete_one({"_id":2})
x = col.insert_one({"_id": 1, "ProcedureCodes": ProcedureCodes})
x = col.insert_one({"_id": 2, "ProcedureCodes": ProcedureCodes})
